#!/usr/bin/bash

# Check if 'parallel' is installed
if ! command -v parallel &>/dev/null; then
	echo "'parallel' is not installed. Installing it..."

	# Check which package manager is available and use the appropriate command
	if command -v apt-get &>/dev/null; then
		sudo apt-get update
		sudo apt-get install parallel -y
	elif command -v yum &>/dev/null; then
		sudo yum install parallel -y
	else
		echo "Unsupported package manager. Please install 'parallel' manually."
		exit 1
	fi

	if [ $? -eq 0 ]; then
		echo "'parallel' has been installed successfully."
	else
		echo "Failed to install 'parallel'. Goodbye :)"
		exit 1
	fi
fi

find . -name "*.py" | sed 's|^\./||' | parallel python3 main.py -f | parallel --colsep ',' "grep -Fxq '{1}' british-english || echo ERROR {3}:line {2}. {4} {5} contains an invalid word: {1}"
